title: "The Ring Ring Company systems status page "
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: At RingRing, transparency is one of our core values. Our
    mission is to provide you a stable and reliable service, and part of that
    promise is keeping you fully informed whenever issues arise. Below, you’ll
    find the current status of RingRing services, as well as any recent issues
    or incidents we may have had. If you're experiencing any problems related to
    our services and don’t see anything about it below, please write us at
    support@ringring.be.
  systems:
    - name: Website
      description: Our company public facing website
      link: https://www.ringring.be/
    - name: Helpdesk
      description: Our company customer support site
      link: https://support.ringring.be/
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: Information about <a class='text-grey-darkest' title='Visit
    www.ringring.be' href='https://www.ringring.be/'>example</a> systems
    operations.<br />Follow us <a class='text-grey-darkest' title='Visit our
    page on Twitter' href='https://www.twitter.com/example'>on Twitter</a> or
    subscribe to <a class='text-grey-darkest' href='%s' >RSS</a><br />to be
    alerted of new events.
  copyrightHolder: The Ring Ring Company
  eventsPerPage: 10
  iconType: image/png
  groups:
    - Website
  icon: /images/clearstatus.png
  description_footer: <a class='text-grey-darkest' title='Visit example.com'
    href='https://www.ringring.be/'>RingRing.be</a> provides world-class
    software for all kind of sectors.
